fixing amd64

diff --git a/containers/Dockerfile b/containers/Dockerfile
--- a/containers/Dockerfile
+++ b/containers/Dockerfile
@@ -33,8 +33,8 @@ COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.
 COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
 COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh
 
-RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
-    /usr/local/bin/_dockerfile_setup_root_prefix.sh
+RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh || (echo "Error in _dockerfile_initialize_user_accounts.sh" && false)
+RUN /usr/local/bin/_dockerfile_setup_root_prefix.sh || (echo "Error in _dockerfile_setup_root_prefix.sh" && false)
 
 USER $MAMBA_USER
 
